In [1]:
##Task 2

##NumPy: is a library for the Python programming language, adding support for large,
# multi-dimensional arrays and matrices,along with a collection of mathematical functions to operate on these arrays.

import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Performing operations on NumPy arrays
arr2 = arr * 2
print(arr2)

# Creating a multi-dimensional array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

# NumPy array operations
print(np.sum(arr))  # Sum of all elements
print(np.mean(arr))  # Mean of all elements
print(np.max(arr))   # Maximum value in the array


[1 2 3 4 5]
[ 2  4  6  8 10]
[[1 2 3]
 [4 5 6]]
15
3.0
5


In [5]:
#Pandas:Pandas is a fast, powerful, and flexible open-source data analysis and manipulation library built on top of the Python programming language.

import pandas as pd

# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}
df = pd.DataFrame(data)
print(df)

# Accessing columns
print(df['Name'])  # Accessing a single column
print(df[['Name', 'Age']])  # Accessing multiple columns

# Filtering rows
filtered_df = df[df['Age'] > 30]
print(filtered_df)




      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston
